mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.zero.system.entity
server:
    port: 808
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            aop-patterns: com.web.springbootdruid.service.*
            filters: stat,wall
            initial-size: 5
            max-active: 20
            max-evictable-idle-time-millis: 400000
            max-open-prepared-statements: -1
            max-wait: 3000
            min-evictable-idle-time-millis: 300000
            min-idle: 5
            pool-prepared-statements: false
            stat-view-servlet:
                allow: 127.0.0.1
                deny: ''
                enabled: true
                reset-enable: false
                url-pattern: /manager/druid/*
            time-between-eviction-runs-millis: 60000
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
                url-pattern: /*
        password: 137158
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.107.241.63:3306/manager_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
    thymeleaf:
        cache: false
        content-type: text/html
        encoding: UTF-8
        mode: LEGACYHTML5
        prefix: classpath:/templates/
        suffix: .html
