mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.zero.system.entity
server:
    port: 808
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            aop-patterns: com.web.springbootdruid.service.*
            filters: stat,wall
            initial-size: 5
            max-active: 20
            max-evictable-idle-time-millis: 400000
            max-open-prepared-statements: -1
            max-wait: 3000
            min-evictable-idle-time-millis: 300000
            min-idle: 5
            pool-prepared-statements: false
            stat-view-servlet:
                allow: ''
                deny: ''
                enabled: true
                reset-enable: false
                url-pattern: /manager/druid/*
            time-between-eviction-runs-millis: 60000
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
                url-pattern: /*
        password: 137158
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.107.241.63:3306/manager_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
    thymeleaf:
        cache: false
        content-type: text/html
        encoding: UTF-8
        mode: LEGACYHTML5
        prefix: classpath:/templates/
        suffix: .html
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

